---
name: "configure-repo-labels"

on:
  push:
    paths:
      - .github/**/*
  workflow_dispatch: {}

jobs:
  configure-repo-labels:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: run-labeler
        if: success()
        uses: crazy-max/ghaction-github-labeler@v2
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
